// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8gqgYr74k27Cge-flxcMjSpkHPVRWbWw',
    appId: '1:1073222841951:web:e54d99b60e5cd61f494dea',
    messagingSenderId: '1073222841951',
    projectId: 'educonnect-cc3f9',
    authDomain: 'educonnect-cc3f9.firebaseapp.com',
    storageBucket: 'educonnect-cc3f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMnUWUkxT_KBZDNdJgSaCqGk-0ysrVe_4',
    appId: '1:1073222841951:android:6df437d2bb892691494dea',
    messagingSenderId: '1073222841951',
    projectId: 'educonnect-cc3f9',
    storageBucket: 'educonnect-cc3f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIN8eeJKzGfECUVz4BX9YmZvk3eWGbMkc',
    appId: '1:1073222841951:ios:681317a471bae085494dea',
    messagingSenderId: '1073222841951',
    projectId: 'educonnect-cc3f9',
    storageBucket: 'educonnect-cc3f9.firebasestorage.app',
    iosBundleId: 'com.example.educonnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIN8eeJKzGfECUVz4BX9YmZvk3eWGbMkc',
    appId: '1:1073222841951:ios:681317a471bae085494dea',
    messagingSenderId: '1073222841951',
    projectId: 'educonnect-cc3f9',
    storageBucket: 'educonnect-cc3f9.firebasestorage.app',
    iosBundleId: 'com.example.educonnectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8gqgYr74k27Cge-flxcMjSpkHPVRWbWw',
    appId: '1:1073222841951:web:e68736009bca8b36494dea',
    messagingSenderId: '1073222841951',
    projectId: 'educonnect-cc3f9',
    authDomain: 'educonnect-cc3f9.firebaseapp.com',
    storageBucket: 'educonnect-cc3f9.firebasestorage.app',
  );

}